### ISSUE TITLE
ExportNamedDeclaration throws unknown error

### ISSUE THREAD

**Issue by justingreenberg** [thejameskyle/babel-plugin-react-pure-components#4]
ExportNamedDeclarations, eg:
```js
export class pureComponent extends React.Component {
  static propTypes = {
    className: React.PropTypes.string.isRequired
  };

  render() {
    return (
      <div className={this.props.className}>
        Transformed JSX String
      </div>
    );
  }
}
```
babel-plugin-react-pure-components throws:
```js
unknown: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```
please see: https://astexplorer.net/#/Q13PK25kdL/11 for replicated **error state**
please see: https://astexplorer.net/#/Q13PK25kdL/12 for **working example** of `export default class`

any ideas? i'm having trouble tracing the error above or which node it's coming from. as usual, any guidance is greatly appreciated and i'm happy to make changes if you steer me in the right direction. 

thank you!

**Comment by thejameskyle** [comment]
The problem is that in that scenario the parent is an `ExportNamedDeclaration` 

Just changing:

```js
path.insertAfter(t.expressionStatement(...
```

to

```js
path.parentPath.insertAfter(t.expressionStatement(...
```

fixes the issue.

However, I'm confused as to why it works with ExportDefaultDeclaration as that should be causing the same problem as far as I can tell.
